engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript

ratings:
  paths:
  - "src/**/*"

exclude_paths:
  - ".vscode/"
  - "android/"
  - "ios/"
  - "flow-typed/"
  - "node_modules/"
